deployments:
- build_id: c2cdd715-d68f-4e2f-b607-372e0506542e
  builder: arkitekt.builders.port
  definitions: []
  deployed_at: '2023-09-21T13:12:47.020411'
  deployment_id: 823ffcd7-215c-4a0e-8ed8-65a29fbc1fcd
  image: jhnnsrs/reaktor:0.0.2
  manifest:
    author: jhnnsrs
    created_at: '2023-09-21T13:12:20.712578'
    entrypoint: app
    identifier: reaktor
    requirements: []
    scopes:
    - read
    version: 0.0.2
latest_deployment: '2023-09-21T13:12:47.020437'
