deployments:
- author: jhnnsrs
  command: python run.py
  created_at: '2023-04-18T12:17:59.717734'
  definitions: []
  entrypoint: app
  identifier: reaktor
  image: jhnnsrs/reaktor:0.0.1
  requirements: []
  scopes:
  - read
  version: 0.0.1
- author: jhnnsrs
  command: python run.py
  created_at: '2023-04-18T12:35:44.588438'
  definitions: []
  entrypoint: app
  identifier: reaktor
  image: jhnnsrs/reaktor:0.0.2
  requirements: []
  scopes:
  - read
  version: 0.0.2
- author: jhnnsrs
  command: python run.py
  created_at: '2023-04-20T13:20:04.004558'
  definitions: []
  entrypoint: app
  identifier: reaktor
  image: jhnnsrs/reaktor:0.0.3
  requirements: []
  scopes:
  - read
  version: 0.0.3
- author: jhnnsrs
  command: python run.py
  created_at: '2023-04-20T13:30:07.615151'
  definitions: []
  entrypoint: app
  identifier: reaktor
  image: jhnnsrs/reaktor:0.0.4
  requirements: []
  scopes:
  - read
  version: 0.0.4
- author: jhnnsrs
  command: python run.py
  created_at: '2023-04-20T14:18:25.704787'
  definitions: []
  entrypoint: app
  identifier: reaktor
  image: jhnnsrs/reaktor:0.0.5
  requirements: []
  scopes:
  - read
  version: 0.0.5
- author: jhnnsrs
  command: arkitekt run port
  created_at: '2023-04-21T16:43:36.485071'
  definitions: []
  entrypoint: app
  identifier: reaktor
  image: jhnnsrs/reaktor:0.0.6
  requirements: []
  scopes:
  - read
  version: 0.0.6
latest_deployment: '2023-04-21T16:43:56.444190'
